# Model Configuration
model:
  embed_dim: 768
  num_heads: 12
  ff_dim: 1024
  dropout: 0.1
  num_layers: 12
  board_vocab_size: 13     # 12 pieces + 1 empty square
  pos_size: 69             # 8x8 board + metadata
  turn_size: 2             # White/Black turn
  castling_size: 2         # Can/Cannot castle
  moves_vocab_size: 1971   # Hypothetical moves vocabulary size

# Game settings
game:
  opponent: "self"  # Options: "self" or "stockfish"
  model_color: "white"  # Options: "white", "black", or "random"
  max_moves: 1000  # Maximum number of moves before declaring a draw
  temperature: 0.7  # Temperature for move sampling (higher = more random)
  top_k: 5  # Number of top moves to consider for sampling

# Stockfish settings (used both for play and training)
stockfish:
  path: "C:\\Program Files\\stockfish\\stockfish-windows-x86-64-avx2.exe"
  games_per_epoch: 12800
  max_workers: 24  # Set to null to use CPU count, or specify a number
  min_elo: 1200
  max_elo: 2800
  max_moves: 200
  min_tc: 5  # Minimum time control (seconds)
  max_tc: 10  # Maximum time control (seconds)
  vary_params: true

# MCTS settings for training and gameplay
mcts:
  enabled: true
  train_method: "continuous"  # "regeneration" or "continuous"
  games_per_epoch: 10
  simulations: 20
  temperature: 1.0
  exploration: 1.0
  dirichlet_noise: true
  dirichlet_alpha: 0.3
  noise_fraction: 0.25
  num_games: 100  # For continuous method
  epochs_per_game: 1  # For continuous method

# Data configuration
data:
  games_dir: "games/"
  output_dir: "training_data/"
  num_games: 10
  batch_size: 32
  max_moves: 100
  temperature: 1.0
  top_k: 5
  stockfish_percentage: 0.0
  predata_path: null

# Training configuration
training:
  epochs: 50  # Number of training epochs
  learning_rate: 0.001  # Learning rate for optimizer
  resume: true  # Whether to resume training from checkpoint
  checkpoint_dir: "checkpoints/"  # Directory to save model checkpoints
  save_frequency: 1  # How often to save model checkpoints (in epochs)
  visualize: true  # Whether to visualize training history
  method: 'mcts'  # Training method: 'mcts', 'self-play', or 'stockfish'

# Checkpoint configuration (for resuming training)
checkpoint:
  path: "C:\\Users\\haoyan\\Documents\\COGS188_group_template-1\\checkpoints\\latest_model.pt"  # Path to checkpoint file for resuming training
  
# Hydra Configuration
hydra:
  run:
    dir: .

# Path to the trained model
model_path: "checkpoints/latest_model.pt"

# Whether to require a model (if false, will use random moves when model not available)
require_model: true

# Player options
player_color: "white"  # "white", "black", or "random"

# Game options
model_thinking_time: 1.0  # Minimum time (in seconds) the model "thinks" before making a move
temperature: 0.5  # Temperature for move selection (higher = more random)
top_k: 3  # Number of top moves to consider