# Model Configuration
model:
  embed_dim: 128
  num_heads: 8
  ff_dim: 256
  dropout: 0.1
  num_layers: 6
  board_vocab_size: 13     # 12 pieces + 1 empty square
  pos_size: 64             # 8x8 board
  turn_size: 2             # White/Black turn
  castling_size: 2         # Can/Cannot castle
  moves_vocab_size: 4672   # Hypothetical moves vocabulary size

# Training Configuration
training:
  batch_size: 64
  num_epochs: 10
  learning_rate: 1e-4
  device: "cuda"

# Data Configuration
data:
  dataset_path: "data\\ML23d.h5"

# Paths
paths:
  model_save_path: "chess_model.pth"

# Hydra Configuration
hydra:
  run:
    dir: .
